### PR TITLE
Add check if libatomic is needed

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Code from LLVM project under LLVM Release License

Discussion in #41

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
This needs further testing. The CMake module blindly assumes that `-latomic` will work. The check to find `libatomic` is disabled as it couldn't find the lib in the compiler specific path.
Perhaps we don't need to find the lib but just try if `-latomic` works? Guess I'll rewrite the module.

**Comment by guruofquality** [comment]
Does this PR need more testing? https://github.com/pothosware/SoapyRTLSDR/issues/47

**Comment by zuckschwerdt** [comment]
I'll tinker with it some more today. It's not great but seems to work. I'm not sure what combination of Atomic/Atomic64 might require `-latomic`. Anyway it's neatly contained in one cmake module and should suffice for now.

**Comment by zuckschwerdt** [comment]
Reworked and simplified the detection logic. Actually looks sane now, merging.

**Pull request merged**
